# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update Data

on: 
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: Update files on GitHub
      uses: test-room-7/action-update-file@v1.6.0
      with:
          file-path: |
            Blacklist/Argentina/chat_blacklist.txt
            Blacklist/Argentina/hashtag_blacklist.txt
            Blacklist/Argentina/search_blacklist.txt
            Blacklist/Brazil/chat_blacklist.txt
            Blacklist/Brazil/hashtag_blacklist.txt
            Blacklist/Brazil/search_blacklist.txt
            Blacklist/Chile/chat_blacklist.txt
            Blacklist/Chile/hashtag_blacklist.txt
            Blacklist/Chile/search_blacklist.txt
            Blacklist/Colombia/chat_blacklist.txt
            Blacklist/Colombia/hashtag_blacklist.txt
            Blacklist/Colombia/search_blacklist.txt
            Blacklist/Indonesia/chat_blacklist.txt
            Blacklist/Indonesia/hashtag_blacklist.txt
            Blacklist/Indonesia/search_blacklist.txt
            Blacklist/Malaysia/chat_blacklist.txt
            Blacklist/Malaysia/hashtag_blacklist.txt
            Blacklist/Malaysia/search_blacklist.txt
            Blacklist/Mexico/chat_blacklist.txt
            Blacklist/Mexico/hashtag_blacklist.txt
            Blacklist/Mexico/search_blacklist.txt
            Blacklist/Philippines/chat_blacklist.txt
            Blacklist/Philippines/hashtag_blacklist.txt
            Blacklist/Philippines/search_blacklist.txt
            Blacklist/Poland/chat_blacklist.txt
            Blacklist/Poland/hashtag_blacklist.txt
            Blacklist/Poland/search_blacklist.txt
            Blacklist/Singapore/chat_blacklist.txt
            Blacklist/Singapore/hashtag_blacklist.txt
            Blacklist/Singapore/search_blacklist.txt
            Blacklist/Spain/chat_blacklist.txt
            Blacklist/Spain/hashtag_blacklist.txt
            Blacklist/Spain/search_blacklist.txt
            Blacklist/Taiwan/chat_blacklist.txt
            Blacklist/Taiwan/hashtag_blacklist.txt
            Blacklist/Taiwan/search_blacklist.txt
            Blacklist/Thailand/chat_blacklist.txt
            Blacklist/Thailand/hashtag_blacklist.txt
            Blacklist/Thailand/search_blacklist.txt
            Blacklist/Vietnam/chat_blacklist.txt
            Blacklist/Vietnam/hashtag_blacklist.txt
            Blacklist/Vietnam/search_blacklist.txt
          commit-msg: Update blacklist word
          github-token: ${{ secrets.GH_TOKEN }}
          branch: main